name: Protocol
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  # format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.head_ref }}
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #     - run: yarn add prettier
  #     - run: yarn add prettier-plugin-solidity
  #     - run: shopt -s globstar; yarn prettier --write --config .prettierrc --plugin=prettier-plugin-solidity "**/*.sol" || true
  #     - name: Commit changes
  #       uses: stefanzweifel/git-auto-commit-action@v4
  #       with:
  #         commit_message: prettier auto formatting changes
  #         branch: ${{ github.head_ref }}
  #     - name: check format
  #       run: shopt -s globstar; yarn prettier --check --config .prettierrc --plugin=prettier-plugin-solidity "**/*.sol"
  test:
    # needs: format    # Removing this since the format job is commented out
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Protocol Tests
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Generate
        id: generate-with-cache
        run: yarn generate

      - name: Clear cache and reinstall on generate failure
        if: steps.generate-with-cache.outcome == 'failure' && steps.node-modules-cache.outputs.cache-hit == 'true'
        run: |
          rm -rf **/node_modules
          yarn install --no-immutable

      - name: Generate (after potential cache clear)
        if: steps.generate-with-cache.outcome == 'failure'
        run: yarn generate

      - name: Run tests
        run: yarn hardhat clean
        run: yarn hardhat test
        env:
          FORKING_RPC: ${{ secrets.ANVIL_FORK_URL }}
          BASE_RPC: ${{ secrets.BASE_RPC }}