name: Protocol
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Protocol Tests
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Generate
        id: generate-with-cache
        run: yarn generate

      - name: Clear cache and reinstall on generate failure
        if: steps.generate-with-cache.outcome == 'failure' && steps.node-modules-cache.outputs.cache-hit == 'true'
        run: |
          rm -rf **/node_modules
          yarn install --no-immutable

      - name: Generate (after potential cache clear)
        if: steps.generate-with-cache.outcome == 'failure'
        run: yarn generate

      - name: Run tests
        run: |
          yarn hardhat clean
          yarn hardhat test
        env:
          FORKING_RPC: ${{ secrets.ANVIL_FORK_URL }}
          BASE_RPC: ${{ secrets.BASE_RPC }}