name: Forge Tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

env:
  FORKING_RPC: ${{ secrets.ANVIL_FORK_URL }}
  ARBITRUM_FORKING_RPC: ${{ secrets.ARBITRUM_FORKING_RPC }}

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Install Libraries
        run: |
          forge install https://github.com/foundry-rs/forge-std@07263d1 --no-commit
          forge install https://github.com/OpenZeppelin/openzeppelin-contracts@fd81a96 --no-commit
          forge install https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable@3d4c0d5 --no-commit
          forge install https://github.com/paulrberg/prb-math@2c59739 --no-commit

      - name: Run Forge build
        run: |
          forge --version
          forge clean
          forge build

      - name: Run Forge tests
        run: forge test
